export const columns = [
  { field: "id", headerName: "ID", width: 33 },
  { field: "registrarId", headerName: "Registar ID" },
  {
    field: "name",
    headerName: "Name",
    flex: 1,
    cellClassName: "name-column--cell",
  },
  {
    field: "age",
    headerName: "Age",
    type: "number",
    headerAlign: "center",
    align: "center",
    width: 44,
    flex: 1,
  },
  { field: "phone", headerName: "Phone Number", flex: 1 },
  { field: "email", headerName: "Email", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "City", flex: 1 },
  { field: "zipCode", headerName: "Zip Code", flex: 1 },
];

export const rows = [
  {
    id: 1,
    name: "jon Die",
    email: "jondie12@gmail.com",
    age: 35,
    phone: "(878)827-7388",
    address: "USA",
    city: "USA",
    zipCode: "2231",
    registrarId: "123123",
  },
  {
    id: 2,
    name: "Mohamed Esam",
    email: "Mohamed2@gmail.com",
    age: 29,
    phone: "+2012 987 095 64",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1233",
    registrarId: "123132",
  },
  {
    id: 3,
    name: "Tarek Helal",
    email: "tatrkhelal@gmail.com",
    age: 22,
    phone: "+2012 111 888 49",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1424",
    registrarId: "123132",
  },
  {
    id: 4,
    name: "Hesham Ahmed",
    email: "He4amahmed@gmail.com",
    age: 30,
    phone: "+2010 292 933 48",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1234",
    registrarId: "123132",
  },
  {
    id: 5,
    name: "Mohsen Hashim",
    email: "mo7sin22@gmail.com",
    age: 32,
    phone: "+2012 8472 1328",
    address: "Egypt-Qairo",
    city: "Qairo",
    zipCode: "3124",
    registrarId: "123132",
  },
  {
    id: 6,
    name: "Mohamed Tarek",
    email: "mohamedtarek0@gmail.com",
    age: 27,
    phone: "+2012 2412 3476",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1224",
    registrarId: "123132",
  },
  {
    id: 7,
    name: "Ziad Galal",
    email: "ziadgalal11@gmail.com",
    age: 42,
    phone: "+2012 8381 2273",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1234",
    registrarId: "123132",
  },
  {
    id: 8,
    name: "Ziad Elbendary",
    email: "ziadelbendary23@gmail.com",
    age: 24,
    phone: "+2011 2312 8319",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1264",
    registrarId: "123132",
  },
  {
    id: 9,
    name: "Abdelrhman Hesham",
    email: "abdelrhamn888@gmail.com",
    age: 34,
    phone: "+2014 0239 1838",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1724",
    registrarId: "123132",
  },
  {
    id: 10,
    name: "Abdelrhman Hesham",
    email: "abdelrhamn888@gmail.com",
    age: 34,
    phone: "+2014 0239 1838",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1854",
    registrarId: "123132",
  },
  {
    id: 11,
    name: "Abdelrhman Hesham",
    email: "abdelrhamn888@gmail.com",
    age: 34,
    phone: "+2014 0239 1838",
    address: "Egypt-Alex",
    city: "Alexandria",
    zipCode: "1254",
    registrarId: "123132",
  },
];
